
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftDISJUNCTIONleftCONJUNCTIONleftNEGATIONleftLESS_THANLESS_THAN_EQUAL_TOEQUAL_TONOT_EQUAL_TOGREATER_THAN_EQUAL_TOGREATER_THANrightCONSleftINleftPLUSMINUSleftTIMESDIVIDEINT_DIVIDEMODrightUMINUSrightRAISED_TO_POWER_OFCOMMA CONJUNCTION CONS DISJUNCTION DIVIDE EQUAL_TO FALSE GREATER_THAN GREATER_THAN_EQUAL_TO HASHTAG IN INTEGER INT_DIVIDE LEFT_BRACKET LEFT_PARENTHESIS LESS_THAN LESS_THAN_EQUAL_TO MINUS MOD NEGATION NOT_EQUAL_TO PLUS RAISED_TO_POWER_OF REAL RIGHT_BRACKET RIGHT_PARENTHESIS STRING TIMES TRUEexpr : propprop : prop PLUS propprop : prop MINUS propprop : MINUS prop %prec UMINUSprop : LEFT_PARENTHESIS prop RIGHT_PARENTHESISprop : INTEGERprop : REAL'
    
_lr_action_items = {'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,],[3,8,3,3,-6,-7,3,3,-4,8,-2,-3,-5,]),'LEFT_PARENTHESIS':([0,3,4,7,8,],[4,4,4,4,4,]),'INTEGER':([0,3,4,7,8,],[5,5,5,5,5,]),'REAL':([0,3,4,7,8,],[6,6,6,6,6,]),'$end':([1,2,5,6,9,11,12,13,],[0,-1,-6,-7,-4,-2,-3,-5,]),'PLUS':([2,5,6,9,10,11,12,13,],[7,-6,-7,-4,7,-2,-3,-5,]),'RIGHT_PARENTHESIS':([5,6,9,10,11,12,13,],[-6,-7,-4,13,-2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),'prop':([0,3,4,7,8,],[2,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> prop','expr',1,'p_expr','sbml.py',204),
  ('prop -> prop PLUS prop','prop',3,'p_prop_plus','sbml.py',209),
  ('prop -> prop MINUS prop','prop',3,'p_prop_minus','sbml.py',214),
  ('prop -> MINUS prop','prop',2,'p_prop_uminus','sbml.py',219),
  ('prop -> LEFT_PARENTHESIS prop RIGHT_PARENTHESIS','prop',3,'p_prop_parenthetical','sbml.py',224),
  ('prop -> INTEGER','prop',1,'p_prop_integer','sbml.py',239),
  ('prop -> REAL','prop',1,'p_prop_real','sbml.py',244),
]
